secrets:
  db_password:
    file: ./secrets/db_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt

networks:
  frontend-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

  backend-network:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.21.0.0/16


services:
  # Database
  database:
    image: postgres:16-alpine
    container_name: todo-database
    restart: unless-stopped

   # ports:
   #  - "5432:5432"

    networks:
      - backend-network

    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    
    secrets:
      - db_password

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:ro

    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
      
    security_opt:
       - no-new-privileges:true  
    
    cap_drop:
      - ALL  
    
    cap_add:
      - CHOWN      
      - SETUID     
      - SETGID     
      - DAC_OVERRIDE  

    stop_grace_period: 60s

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todouser -d todoapp"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M

  # backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: todo-backend
    restart: unless-stopped

      #user: "0:0"
    user: "1000:1000"  

    networks:
      - frontend-network
      - backend-network

    ports:
      - "3000:3000"

    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=todoapp
      - DB_USER=todouser

    secrets:
    - db_password
    - jwt_secret

    depends_on:
      database:
        condition: service_healthy
    
   
    read_only: true
    tmpfs:
      - /tmp
      - /app/tmp
      
      
    security_opt:
       - no-new-privileges:true
    
    cap_drop:
      - ALL 
     
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - FOWNER  
    
    mem_limit: 512m
    cpus: "0.5"
    pids_limit: 100
    
    stop_grace_period: 30s

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    logging:
     driver: "json-file"
     options:
       max-size: "10m"
       max-file: "3"
    
  # frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    restart: unless-stopped

    networks:
      - frontend-network

    ports:
      - "80:80"

    depends_on:
      backend:
        condition: service_healthy

    read_only: true
    tmpfs:
      - /tmp
      - /var/run
      - /var/cache/nginx  
      
    
    security_opt:
       - no-new-privileges:true
    
    cap_drop:
      - ALL
    
    cap_add:
      - CHOWN       
      - SETUID      
      - SETGID      
      - NET_BIND_SERVICE 
    
    mem_limit: 512m
    cpus: "0.5"
    pids_limit: 50

    stop_grace_period: 20s

    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  pgdata:
    driver: local
